fix: checkstyle's configFile was erroneous
ekino/gradle-quality-plugin pull request #15
Opened 2019-11-15 10:20 UTC by fthouraud

fix #14

2019-11-15 12:17 UTC, Crow-EH commented
Seems like unbroken-dome test-sets 2.1.0 is unreachable (tahnks @saugereau).
@fthouraud you'll have to upgrade it to fix it I think.

2019-11-15 20:35 UTC, Crow-EH commented
The tests are still failing.

As we discussed with @fthouraud and @saugereau, it may be due to [Gradle's recent upgrade of TLS from 1.2 to 1.3](https://status.gradle.com/incidents/q2vq49fndxg0). There is a [issue on JDK regarding TLS 1.3](https://bugs.openjdk.java.net/browse/JDK-8213202) (that Gradle links to in the previous link) that has been fixed in 11.0.3.

Sadly, Travis still installs JDK 11.0.2 (see tests logs) due to its use of https://github.com/sormuras/bach/. Bach doesn't want to change its JDK download source (https://github.com/sormuras/bach/pull/89), even though [java.net is clearly only storing old archives of JDK 11](http://jdk.java.net/archive/).

2019-11-18 09:02 UTC, fthouraud commented
Thanks @Crow-EH for the summary.

Bach removed the support for Oracle & AdoptOpenJDK so I don't think we could manage to change his mind.
But, there's still an easier solution considering that we can specify a custom URL to `install-jdk.sh` with the `--url` flag (cf [Bach's comment](https://github.com/sormuras/bach/issues/51#issuecomment-487385445)).

I never used GitHub Actions but I won't doubt it would be funnier :smile:

2019-11-19 15:46 UTC, saugereau requested changes

2019-11-19 15:46 UTC, saugereau commented on .travis/build.sh
> +./gradlew build --info --stacktrace
Can you remove --info and --stacktrace ?

2019-11-19 16:28 UTC, Crow-EH approved these changes

2019-11-19 16:29 UTC, Crow-EH commented
LGTM :+1:

2019-11-19 16:32 UTC, saugereau approved these changes

2019-11-19 16:33 UTC, merged